Repository HewlettPackard/hpegl-metal-terraform-resources, pull requests merged in 2023-03, with the labels that each got.

#105 bump hpegl-metal-client to v1.14.16
  go.mod
  go.sum
Labels: dependencies

#106 DE11256 fix host delete to always be synchronous
  internal/resources/resource_host.go
Labels: bug

#107 Force upgrade of golang.org/x/net to satisfy CVE
  go.mod
  go.sum
Labels: dependencies, go
